### PR TITLE
check temperatures more often during PID autotune

### PR DESCRIPTION
**Pull request by triffid**
also tolerate 55c overshoot- default temp is 150c, 205 is not dangerous for hotends

### CODE REVIEW

**Comment by midopple** [comment]
Hi,

The Define #define HEATER_CHECK_INTERVAL 100 is not used for Autotune, only for Heater PID control or ON / OFF Control.

For Autotune there is a fix Value
Check every 100 ms the Temperatur and calculate every 1sec the Autotune values

**Comment by triffid** [comment]
hm ok, I'm getting 50-60c overshoot when I run PID autotune, thought it might not be checking often enough.. it leaves the heater on for a few seconds after it reports exceeding the target over serial which sure doesn't help. Seems to be a few hardcoded 5000ms timeouts in there although I don't understand the algorithm well enough to see their exact purpose just yet

**Comment by midopple** [comment]
Next days i check the sourcecode and change the overshot value.

**Comment by midopple** [comment]
Hi,

I have change the Overshot value to 55 °C
The cycletime is the same, i need it for calc the I-Factor.

see: https://github.com/kliment/Sprinter/tree/experimental

**Pull request closed without merging**
