### PR TITLE
Added parameter support to G28. Fixed format of M114 and M105 to conform to GCode spec.

### PR DESCRIPTION
**Pull request by geoffd123**
Hi Kilment.

Here are 3 commits.

1) To add support for X, Y, Z parameters on G28.

2) The return message for M105 did not start with 'ok' this meant that ReplicatorG hangs as it never received an ok on response to M105.

The return message for M114 did not conform to the reprap wiki gcode spec.  It should start with C: and have spaces between xn.nn yn.nn etc.

3) Unfortunately I also committed changes to my config for my machine first and I could not find a away to exclude this commit in the pull request.  When you merge can you ignore any changes to configuration.h.

Cheers
Geoff Drake

### CODE REVIEW

**Comment by caru** [comment]
Sorry for the late response.

1) What if I just want to issue a "G28" without specifying axes? Your code wouldn't do anything, I don't think that's convenient.

2) I am not sure about this, in particular I am not sure it will remain compatible with the various Repsnapper versions. Kliment, what do you think?

3) You could just clone again Sprinter in a different folder, for example. BTW, in general, it is best to do one commit per pull request, unless multiple commits have been done for the very same feature/functionality. But don't be afraid to do pull requests anyway, even if you don't follow this suggestions ;)

**Comment by geoffd123** [comment]
Hi Caru

> Sorry for the late response.

No problem.

> ) What if I just want to issue a "G28" without specifying axes? Your code wouldn't do anything, I don't think that's convenient.

G28 should continue to work as normal, but if you do a G28 X0 etc. it will only zero that axis.  The segment if axis == false will trigger the zero if no axis has been set

   if( (axis_set == false || code_seen('X') 

> 2) I am not sure about this, in particular I am not sure it will remain compatible with the various Repsnapper versions. Kliment, what do you think?

I have never got Repsnapper to run on my Mac, so I cannot test it.  But according to the gcode spec that is the correct format, so Repsnapper might be coded wrong too :)  

> 3) You could just clone again Sprinter in a different folder, for example. BTW, in general, it is best to do one commit per pull request, unless multiple commits have been done for the very same feature/functionality. But don't be afraid to do pull requests anyway, even if you don't follow this suggestions ;)

Thanks for the advice. I will bear this in mind for the future.  I have only just started using pull requests and still have a bit to learn :)

Cheers
Geoff

**Comment by caru** [comment]
1) Ok, I see. If Kliment is not against this, I think this can be merged.

2) Nonetheless, we have to deal with Repsnapper, as that's what 90% of the users use. Have you tried to install the modified ReplicatorG compatible with Sprinter? I remember BenJackson modified and published it, you can find it here http://ben.com/reprap/

**Comment by geoffd123** [comment]
Hi Caru

I finally got Repsnapper to run on my machine and with my temperature mod it does not monitor the temperature, without it it does.

I tried Bens ReplicatorG, without my temperature and M114 mod it does not work, with my temperature mod it does.  So RepG is coded to the spec whilst Repsnapper is not.

As you say a lot of your users are running Repsnapper, so you have to leave it as is.

I am having lots of problems with both Repsnapper and ReplicatorG.  I am using Skeinforge 40.  Sometimes I create a file and when I print it it runs ok but there are problems.  I tweek one parameter such as raft size run it again and the whole print goes haywire with it printing random lines in random places.

I have yet to find a tool chain that works reliably with Gen6, either the standard firmware or Sprinter.

Cheers
Geoff

**Comment by caru** [comment]
geoffd123, we can have both.
if would be happy to have an optional replicatorG mode where you can just enable a #define in configuration.h, for example:
//Uncomment the following line to have firmware send GCODE compliant responses (eg: useful if you print with ReplicatorG)
//#define GCODE_COMPLIANT_RESPONSE_MODE 1

Then in tonokipfirmaware.pde in the M105 and M114 response code you put in something like:

#ifdef GCODE_COMPLIANT_RESPONSE_MODE
  //here your code
#else
  //here the old code
#endif

What do you think?

For repsnapper, i'd try to find help in #reprap or #repsnapper channels on IRC.

**Comment by geoffd123** [comment]
Hi Caru

That sounds good.

I will rework the code shortly.

Cheers
Geoff

**Pull request closed without merging**
