### PR TITLE
A very flexible and reliable way for individuals add customized code to the firmware, without modifying Tonokip_Firmware.pde file.

### PR DESCRIPTION
**Pull request by hradec**
by defining CUSTOM_SETUP macro in configuration.h, with the name of a custom setup function defined by you, the setup() function will automatically execute it.
the same for loop, but using the CUSTOM_LOOP macro.

This is a very flexible way for individuals add their own customized code to the firmware, keeping the main files untouched and totally fine to receive the latest updates.

If those macros are undefined (which they will be on the head) the compiler will just ignore it.

Why do we need custom setup/loop code: 

1.my ramps board has some extra pins connected to MS1, MS2 and MS3 of the pololu drivers, so I can set 4/8/16 microsteps logically. Using the CUSTOM_SETUP macro, I made the setup() function initialize those pins properly.
1. I also use the CUSTOM_SETUP to make the arduino calculate the thermistor table for me on the fly, once every reboot, so I don't have to care about using python scripts. Based on this forum entry:
   
   http://www.arduino.cc/playground/ComponentLib/Thermistor2

I use "The Elaborated Code" to calculate my table on the arduino itself, so I just have to enter 

float pad = < the measured resistance of your pad resistor >;
float thermr = <thermistor nominal resistance>;

in my configuration file and the table gets automagically created. If I want to use the firmware with another thermistor, just re-mesure booth pad resistor and thermistors with a multimeter, and update those constants.

### CODE REVIEW

**Comment by caru** [comment]
This is very nice and clean!
Would you mind adding the two commented #defines in configuration.h, possibly with some very brief documentation about their purpose and how to use them?
Then please do a pull request again and I will merge it.
Tnx!

**Comment by hradec** [comment]
Hi there... sorry it took me while, but I finally got my fork up2date, and added the example code for the custom code setup I mentioned about. 

Also, I added an option to include a CUSTOM configuration file into  Configuration.h, by just uncommenting one include line. This should allow for easier setup of individual machines without modifying the main Configuration.h, apart from that include line. 

It should make MUUUCH easier to do merges to the HEAD.

**Comment by hradec** [comment]
this should be my last one... I added an option to pins.h to allow for a custom pinage header file. In case people has a different pinage setup for some reason (like I have), they can setup their own pins without modifying the original pins.h!

**Comment by hradec** [comment]
I think I forgot this one... I added a table number 7 for the Honeywell 100K Thermistor (135-104LAG-J01), found on the reprap wiki with the other ones:

http://reprap.org/wiki/Thermistor#Honeywell_100K_Thermistor_.28135-104LAG-J01.29

**Comment by hradec** [comment]
I added a couple of macros to define custom GCode and MCode without modifying the main files. Usage example is in Configuration.h, right below example code for custom setup and loop.

**Comment by hradec** [comment]
One more thing... I tried to add a new pull request as Caru asked, but github doesn't let me do it. It says this one already exists.

**Comment by hradec** [comment]
Are you guys still interested in this changes??

**Pull request closed without merging**
