### PR TITLE
Parametric acceleration distance and Z-speed limiting

### PR DESCRIPTION
**Pull request by ahmetcemturan**
Acceleration distance is now dependent on the difference of the squares of min_units_per_second  and feedrate.
Acceleration is now a new parameter for tuning.  (can be made to enter motor torque and moved mass to calculate acceleration factor)

Also the problem of Z speed:  I calculate Z speed differently.  This way Repsnapper works as well as SF

### CODE REVIEW

**Comment by caru** [comment]
I would add the variable acceleration distance as optional only (eg: with a #define). Also, in my opinion, it is better to define a travel_acceleration in configuration.h rather than adding a magic number to calculate it in the .pde.

I don't understand what are you doing to calculate z speed. Seems like you just add a magic number (zspeed*60) that hence calculates a lower speed. If so, I don't think that's the right approach. It would be much more useful to just add a max_z_feedrate in configuration.h and limit z based on that, rather than have users try to guess what's going on with their z-speed.

**Comment by cakeller98** [comment]
---

## in configuration.h:

add:
float max_z_feedrate = 210; // works well for me, might be too fast for others.

---

## in Tonokip_Firmware.pde:

@(line 104) float feedrate = 1500, next_feedrate;
(add line 105)+ float z_feedrate = max_z_feedrate;

@(line 503) change to: #define Z_TIME_FOR_MOVE ((float)z_steps_to_take / (z_steps_per_unit*z_feedrate/60000000))

@(line 872)  if(feedrate > max_feedrate) feedrate = max_feedrate;
(add line 873)+  if(feedrate > max_z_feedrate) z_feedrate = max_z_feedrate;

---

## Sorry if this is bad form, I'm new to Github.... Hope this helps, it seems to have fixed my problem with excessive Z-Feed from SF... which doesn't seem to know how to obey the "limit" module... anyway. this works for any move diagonal or otherwise.  :)

**Comment by cakeller98** [comment]
Sorry, my bad... you do have to SET the z_feedrate somewhere... otherwise, durr - it'll be constant.

@(line 872)  if(feedrate > max_feedrate) feedrate = max_feedrate;
(add line 873)+  if(feedrate > max_z_feedrate) z_feedrate = max_z_feedrate; else z_feedrate=feedrate;

**Comment by ahmetcemturan** [comment]
Hi Caru,

Originally what I did there is to divide my steps per mm for the z axis and the steps per mm for the X-axis..
float x_steps_per_unit = 40.075; 
float y_steps_per_unit = 40.100;
float z_steps_per_unit = 3394.697;

3394/40= 85 to get a reasonable feedrate that the Z-axis is capable to cope with...  Then I changed it to make it a bit faster..  Thats how I came to that magic number (fort he mendel..)

Or for the Prusa:

float x_steps_per_unit = 80.376;
float y_steps_per_unit = 80.376;
float z_steps_per_unit = 3200/1.25;

3200/80= 32  

Also actually I noticed that one should not post anything after 2:00am.
The Formula was wrong anyway.  (should be: (sq(feedrate)-sq(min_units_per_second))/(2*acceleration_rate)/1000  )
And I will work on it a bit more...  
I totally mixed up two different codes during posting.  I noticed that yesterday evening.. :(

Is the implementation of this too heavy for the processor?  (I am trying to play around with this..)
http://www.hwml.com/LeibRamp.pdf

Thanks for all your work...

-----Original Message-----

**Comment by caru** [comment]
@ahmetcemturan
"3394/40= 85 to get a reasonable feedrate that the Z-axis is capable to cope with"
This is what is wrong... you are just limiting everyone's z speed based on your experience, but someone may have better motors, more current, different rig, etc. The user should be able to set their max z speed, no need for us to guess what a reasonable z speed may be.

"Is the implementation of this too heavy for the processor?"
If you need to calculate a new interval at each step, it probably is. If it is only time dependent, it's more probable it can work. However, I have ramp acceleration almost ready, and will push that option by the end of this week.

**Comment by caru** [comment]
@cakeller98
"this works for any move diagonal or otherwise."
Good to know you already tested that. It would be best you do a clean patch and commit, and then ask for a pull request, so it can automatically be merged. However, just writing the code like that is fine, only it will take more time to add that.

**Comment by caru** [comment]
@ahmetcemturan I'd really like to add your "max acceleration" code as an option, but your diff is a mess. Either pull request a clean diff or give me a clear summary of what exactly i need to add, like cakeller98 did.

**Comment by cakeller98** [comment]
@Caru, I see that you added the patch as suggested. :) Cool!

**Comment by caru** [comment]
@cakeller98: i just saw your original comment, don't worry about messing up ;) if you are interested, this crash course will get you up and running very quickly with git: http://gitref.org/

**Comment by dpslwk** [comment]
"excessive Z-Feed from SF... which doesn't seem to know how to obey the "limit" module"

@cakeller98
if you activate the home tab and just stick 'M105'  in the homing.gcode alterations file SF will the correctly filer the Z moves between layers to just move Z and limit will then be applied correctly
im not sure if there's a better way around this but i know a few people use this trick

**Comment by cakeller98** [comment]
@caru: thanks will look into it - I have some other things I'd like to contribute to this project as well.
@dpslwk: cool thanks for the tip - however, it's still a good idea to have the firmware limit the device to it's capabilities, and prevent erroneous commands from BREAKING the machine ;)... not that you were saying otherwise.

**Pull request closed without merging**
